apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vieng
  namespace: vieng
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  rules:
    - host: vieng.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: vieng-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vieng-frontend
                port:
                  number: 80
